name: Andy Henson
url: http://www.elaptics.co.uk
description: The personal blog of Andy Henson.
future:      false
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink: /journal/:title
exclude: [vendor]
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jekyll-youtube
collections:
  marginalia:
    output: true
    permalink: /marginalia/:path/

defaults:
  -
    scope:
      path: "marginalia" # an empty string here means all files in the project
      type: "marginalia"
    values:
      layout: "marginalia"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
