name: Andy Henson
url: http://www.elaptics.co.uk
description: The personal blog of Andy Henson.
future:      false
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink: /:year/:month/:title
kramdown:
  input: GFM
