name: Andy Henson
url: http://www.elaptics.co.uk
description: The personal blog of Andy Henson.
future:      false
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink: /journal/:title
exclude: [vendor]
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from


